# -*- coding: utf-8 -*-
"""Ryann Mack - Lab 5 Conservation (C25).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nkl6bwUXXE8f9BVv8Swxa-Yq6DfUwfrK
"""

############ COLLISIONS Changes in Momentum and Kinetic Energy##############
####Please note the code below is for ONE cart; You need to do the same for the second cart####


### 1: Calculates propagation of uncertainty for velocity of cart a ####
### Units for velocity are m/s###
###initial velocity (from statistics analysis of velocity graph)###
v_ai = float(input("Enter your initial velocity v_ai in m/s: "))
print("initial velocity in m/s:", v_ai)

###uncertainty of initial velocity (this is the standard deviation on your LoggerPro graph)###
dv_ai = float(input("Enter your uncertainty in initial velocity in m/s: "))
print("uncertainty in initial velocity:", dv_ai)

###final velocity v_af (from statistics analysis of velocity graph)##
v_af = float(input("Enter your final velocity v_af in m/s: "))
print("final velocity in m/s:", v_af)

#uncertainty of final velocity (this is the standard deviation on your LoggerPro graph)
dv_af = float(input("Enter your uncertainty in final velocity in m/s: "))
print("uncertainty in final velocity:", dv_af)

####For more information about propogating uncertainty for items that use addition or subtraction please see Lab 1.

#change in velocity
delta_va = v_af - v_ai
print ("delta_va=", delta_va)

#propogation of uncertainty for the velocity change
dva = dv_ai + dv_af #propogation of uncertainty for velocity
print ("dva=", dva)

###########Repeat for the SECOND CART m_b####################################
### 1: Calculates propagation of uncertainty for velocity of cart b ###
### Units for velocity are m/s
#initial velocity (from statistics analysis of velocity graph)

v_bi = float(input("Enter your initial velocity v_bi in m/s: "))
print("initial velocity v_bi in m/s:", v_bi)

#uncertainty of initial velocity (this is the standard deviation on your LoggerPro graph)
dv_bi = float(input("Enter your uncertainty in initial velocity dv_bi in m/s: "))
print("uncertainty in initial velocity:", dv_bi)

#final velocity v_bf (from statistics analysis of velocity graph)
v_bf = float(input("Enter your final velocity v_bf in m/s: "))
print("final velocity v_bf in m/s:", v_bf)

#uncertainty of final velocity of second cart(this is the standard deviation on your LoggerPro graph)
dv_bf = float(input("Enter your uncertainty in final velocity v_bf in m/s: "))
print("uncertainty in final velocity:", dv_bf)

####For more information about uncertainty please review Lab#1###
###change in velocity###
delta_vb = v_bf - v_bi
print ("delta_vb=", delta_vb)

###propogation of uncertainty for the velocity change###
dvb = dv_bi + dv_bf #propogation of uncertainty for velocity
print ("dvb=", dvb)

###Calculates momentum P and propagation of uncertainty of momentum dP for EACH CART###

####Please note the code below is for ONE cart; You need to do the same for the second cart####


### 1: Calculates propagation of uncertainty for velocity of cart a ####
### Units for velocity are m/s###
###initial velocity (from statistics analysis of velocity graph)###

v_ai = float(input("Enter your initial velocity v_ai in m/s: "))
print("initial velocity in m/s:", v_ai)

###uncertainty of initial velocity (this is the standard deviation on your LoggerPro graph)###
dv_ai = float(input("Enter your uncertainty in initial velocity in m/s: "))
print("uncertainty in initial velocity:", dv_ai)

###final velocity v_af (from statistics analysis of velocity graph)##
v_af = float(input("Enter your final velocity v_af in m/s: "))
print("final velocity in m/s:", v_af)

#uncertainty of final velocity (this is the standard deviation on your LoggerPro graph)
dv_af = float(input("Enter your uncertainty in final velocity in m/s: "))
print("uncertainty in final velocity:", dv_af)

####For more information about propogating uncertainty for items that use addition or subtraction please see Lab 1.

#change in velocity
delta_va = v_af - v_ai
print ("delta_va=", delta_va)

#propogation of uncertainty for the velocity change
dva = dv_ai + dv_af #propogation of uncertainty for velocity
print ("dva=", dva)


### Mass of cart in kilograms###
###measured mass of the cart in kg###
m_a = float(input("Enter your cart 1 mass m_a in kg: "))
print("m_a in kg:", m_a)

###uncertainty in mass - precision of triple beam balance###
dm_a = float(input("Enter your uncertainty in mass in kg: "))
print("uncertainty in m_a in kg:", dm_a)

###Initial momentum P_ai for cart a ###
P_ai = (m_a * v_ai)

print ("Pai=", P_ai)

if v_ai == 0:
    p_ai = 0
    dP_ai=0
else:
####Calculates the uncertainty in initial momentum for car a###

    dP_ai = P_ai * ((dm_a/m_a)+((dv_ai)/abs(v_ai)))
print ("dPai=", dP_ai)

###Final momentum P_af for car a###
P_af = (m_a * v_af)

print ("Paf=", P_af)

###Calculates the uncertainty in FINAL momentum for car a###
dP_af = P_af * ((dm_a/m_a)+((dv_af)/abs(v_af)))
print ("dPaf=", dP_af)


#####REPEAT for CART 2#####

### Mass of cart in kilograms###
#measured mass of the cart in kg###
m_b = float(input("Enter your second cart mass m_b in kg: "))
print("m_b kg:", m_b)

###uncertainty in mass - precision of triple beam balance###
dm_b = float(input("Enter your uncertainty in mass in kg: "))
print("uncertainty in m_b in kg:", dm_b)

###Initial momentum P_bifor car b##
P_bi = (m_b * v_bi)

print ("Pbi=", P_bi)

#### Calculates the uncertainty in momentum P_bi for car b ###
if v_bi == 0:
    p_bi = 0
    dP_bi=0
else:
    dP_bi = P_bi * ((dm_b/m_b)+((dv_bi)/abs(v_bi)))
print ("dPbi=", dP_bi)

### Final Momentum for car b ###

P_bf = (m_b * v_bf)
print ("P_bf=", P_bf)
### Calculates the uncertaint in FINAL momentum P_bf for car b###
dP_bf = P_bf * ((dm_b/m_b)+((dv_bf)/abs(v_bf)))
print ("dP_bf=", dP_bf)

#### Calculates INITIAL and FINAL MOMENTUM for the SYSTEM of TWO CARTS ###


P_i = (m_a * v_ai) + (m_b * v_bi)

print ("P_i=", P_i)

### NOTE: We have already calculated the uncertainty of the initial and final momentum ###
### dP_ai and dP_bi we have in previous cell ###
dP_i = dP_ai + dP_bi
print ("dP_i=", dP_i)

#### Calculates FINAL MOMENTUM for the SYSTEM ###

P_f = (m_a * v_af) + (m_b * v_bf)
print ("P_f=", P_f)
dP_f = dP_af + dP_bf
print ("dP_f=", dP_f)

### Calculates the Uncertainty of FINAL MOMENTUM for the SYSTEM ###

### Note: We calculated dP_af and dP_bf ###
dP = dP_af + dP_bf
print ("dP=", dP)

### Calculates the change of momentum of the system delta_P=dP_f - dP_i ###
delta_P = P_f - P_i
print ("delta_P=", delta_P)

### Prints the uncertainty of change of momentum dP (we calculated this before)###

print("change in momentum:",delta_P,"±",dP," kg * m/s")

### Calculates Kinetic Energy for each car and the SYSTEM ###

### Initial Kinetic Energy K_i BEFORE COLLISION ###
K_ai = ((m_a * v_ai**2)/2)

print("K_ai",K_ai)

K_bi= ((m_b * v_bi**2)/2)
print("K_bi",K_bi)

K_i = K_ai + K_bi

print ("K_i=", K_i)

### FINAL Kinetic Energy K_f AFTER COLLISION ###
K_af = ((m_a * v_af**2)/2)

K_bf = ((m_b * v_bf**2)/2)

print("K_af",K_af)


print("K_bf",K_bf)

K_f = K_af + K_bf
print ("K_f=", K_f)

#### Change in Kinetic Energy ###

delta_K=K_f-K_i
print ("delta_K=", delta_K)

### Uncertainty of Kinetic Energy - INITIAL for each cart ###
if v_ai == 0:
    K_ai = 0
    dK_ai=0
else:
    dK_ai = K_ai * ((dm_a/m_a)+2 * ((dv_ai)/abs(v_ai)))

if v_bi == 0:
    K_bi = 0
    dK_bi=0
else:
    dK_bi = K_bi * ((dm_b/m_b)+2 * ((dv_bi)/abs(v_bi)))

### Uncertainty Initial Kinetic Energy for both carts###

dK_i=dK_ai + dK_bi
dK_i=dK_ai + dK_bi

print ("dK_ai=", dK_ai)
print ("dK_bi=", dK_bi)
print ("dK_i=", dK_i)


#### Uncertainty of Kinetic Energy - FINAL for each car ###
dK_af = K_af * ((dm_a/m_a)+ 2 * ((dv_af)/abs(v_af)))

dK_bf = K_bf * ((dm_b/m_b)+ 2 * ((dv_bf)/abs(v_bf)))

print ("dK_af", dK_af)
print ("dK_bf", dK_bf)

### Uncertainty Final Kinetic Energy for both carts###
dK_f= dK_af + dK_bf

print ("dK_f=", dK_f)

###Uncertainty of Kinetic Energy

dK=dK_f - dK_i
print ("dK=", dK)

print("change in Kinetic Energy delta_K =",delta_K,"±",dK," J")